config/routes.rb
Neptune::Application.routes.draw do
  resources :contacts do
    collection do
      post :import
      get :templete
    end
  end

  resources :clients do
    collection { post :import }
  end

  resources :products do
    collection { post :import }
  end

  devise_for :users

  root 'home#index'

  

end

app/models/client.rb
class Client < ActiveRecord::Base
	Types = ["医院","药店","社区","新农合"]
	Grade = ["一级","二级","三级","私立","药店","诊所","社区","乡镇卫生院","村镇卫生所"]
	Terminal = ["第一终端","第二终端","第三终端","第四终端"]

	has_many :contacts

	include OpenSpreadsheet

	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		header = spreadsheet.row(1)
		(2..spreadsheet.last_row).each do |i|
			row = Hash[[header, spreadsheet.row(i)].transpose]
			product = find_by_id(row["id"]) || new
			product.attributes = row.to_hash.slice(*Client.attribute_names())
			product.save!
		end
	end
	
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: ClientsDatatable.new(view_context) }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  def import
    Client.import(params[:file])
    redirect_to clients_url, notice: "Clients imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :grade, :address, :types, :terminal, :bed, :staff)
    end
end

app/views/clients/_form.html.erb
<div class="block block-themed block-last">
  <div class="block-title">
    <h4>General Form Elements &amp; Components</h4>
  </div>
  <div class="block-content">
    <h4 class="sub-header">基本数据</h4>
    <%= form_for(@client, html: { class: "form-horizontal" }) do |f| %>
    <div class="form-group">
      <%= f.label :name, "名称", class: "control-label col-md-2" %>
      <div class="col-md-6">
        <%= f.text_field :name, class: "form-control" %>
        <span class="help-block">终端的备案名称("XX省XX市XX")</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :types, "分类", class: "control-label col-md-2" %>
      <div class="col-md-2">
       <%= f.select :types, Client::Types, {include_blank: true}, {class: "form-control"} %>
       <span class="help-block">终端类型</span>
      </div>
      <div class="col-md-2">
       <%= f.select :grade, Client::Grade, {include_blank: true}, {class: "form-control"} %>
       <span class="help-block">终端等级</span>
      </div>
      <div class="col-md-2">
       <%= f.select :terminal, Client::Terminal, {include_blank: true}, {class: "form-control"} %>
       <span class="help-block">所属终端</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :bed, "数据", class: "control-label col-md-2" %>
      <div class="col-md-3">
       <%= f.text_field :bed, class: "form-control" %>
       <span class="help-block">床位数</span>
      </div>
      <div class="col-md-3">
       <%= f.text_field :staff, class: "form-control" %>
       <span class="help-block">员工数</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :address, "地址", class: "control-label col-md-2" %>
      <div class="col-md-6">
        <%= f.text_field :address, class: "form-control" %>
        <span class="help-block">终端的详细地址("XX省XX市XX街道XX路XX号")</span>
      </div>
    </div>
    <div class="form-group form-actions">
      <div class="col-md-10 col-md-offset-2">
        <button type="reset" class="btn btn-danger"><i class="icon-repeat"></i> 重置</button>
        <button type="submit" class="btn btn-success"><i class="icon-ok"></i> 提交</button>
      </div>
    </div>
    <% end %>
    <% if @client.new_record?() %>
    <h4 class="sub-header">上传模板数据</h4>
    <%= form_tag import_clients_path, multipart: true, class: "form-horizontal" do %>
    <div class="form-group">
      <label class="control-label col-md-2" for="file">目标数据模板</label>
      <div class="col-md-4">
        <%= file_field_tag :file, class: "form-control" %>
      </div>
    </div>  
    <div class="form-group form-actions">
      <div class="col-md-10 col-md-offset-2">
        <button type="submit" class="btn btn-success"><i class="icon-cloud-upload"></i> 上传</button>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/clients/edit.html.erb
<%= render 'form' %>

app/views/clients/index.html.erb
<% provide(:page_title, page_title("glyphicon-shopping_bag","终端列表","这里可以查询所有终端客户信息")) %>
<div class="block-section">
	<table class="ddatatabless table table-bordered table-hover" data-source="<%= clients_url(format: "json") %>">
		<thead>
			<tr>
				<th><i class="icon-user"></i> 终端名称</th>
				<th> 终端类型</th>
				<th> 终端等级</th>
				<th> 所属终端</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>

app/views/clients/new.html.erb
<% provide(:page_title, page_title("glyphicon-shopping_bag","新增终端","这里添加终端的详细信息")) %>
<%= render 'form' %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @client.grade %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @client.tel %>
</p>

<p>
  <strong>Website:</strong>
  <%= @client.website %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @client.employee %>
</p>

<p>
  <strong>Turnover:</strong>
  <%= @client.turnover %>
</p>

<p>
  <strong>Intro:</strong>
  <%= @client.intro %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>