config/routes.rb
Neptune::Application.routes.draw do
  resources :contacts do
    collection do
      post :import
      get :templete
    end
  end

  resources :clients do
    collection { post :import }
  end

  resources :products do
    collection { post :import }
  end

  devise_for :users

  root 'home#index'

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :client

	include OpenSpreadsheet

	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		header = spreadsheet.row(1)
		(3..spreadsheet.last_row).each do |i|
			row = Hash[[header, spreadsheet.row(i)].transpose]
			contact = find_by_id(row["id"]) || new
			contact.attributes = row.to_hash.slice(*Contact.attribute_names())
			contact.client = Client.find_by_name(row["client_id"])
			contact.save!
		end
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: ContactsDatatable.new(view_context) }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  def import
    Contact.import(params[:file])
    redirect_to contacts_url, notice: "Contacts imported."
  end

  def templete
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :department, :duty, :age, :client_id, :sex, :birthdate, :address, :mobile, :tel, :email, :tencent, :idcard, :hobby, :nation, :marital, :blood, :height, :weight, :zodiac, :school, :science, :note)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<div class="block block-themed block-last">
  <div class="block-title">
    <h4>General Form Elements &amp; Components</h4>
  </div>
  <div class="block-content">
    <h4 class="sub-header">基本数据</h4>
    <%= form_for(@contact, html: { class: "form-horizontal" }) do |f| %>
    <div class="form-group">
      <%= f.label :name, "资料", class: "control-label col-md-2" %>
      <div class="col-md-2">
        <%= f.text_field :name, class: "form-control" %>
        <span class="help-block">姓名</span>
      </div>
      <div class="col-md-2">
        <%= f.select :sex, ["男","女"], {include_blank: true}, {class: "form-control"} %>
        <span class="help-block">性别</span>
      </div>
      <div class="col-md-2">
        <%= f.date_field :birthdate, class: "form-control" %>
        <span class="help-block">出生日期</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :department, "工作信息", class: "control-label col-md-2" %>
      <div class="col-md-3">
        <%= f.select :client_id, Client.all.map{ |c| [c.name, c.id] }, {include_blank: true}, {class: "form-control"} %>
        <span class="help-block">所属终端</span>
      </div>
      <div class="col-md-2">
        <%= f.text_field :department, class: "form-control" %>
        <span class="help-block">所属部门</span>
      </div>
      <div class="col-md-2">
        <%= f.text_field :duty, class: "form-control" %>
        <span class="help-block">职务</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :mobile, "联系方式", class: "control-label col-md-2" %>
      <div class="col-md-2">
        <%= f.text_field :mobile, class: "form-control" %>
        <span class="help-block">手机</span>
      </div>
      <div class="col-md-2">
        <%= f.text_field :tel, class: "form-control" %>
        <span class="help-block">座机</span>
      </div>
      <div class="col-md-2">
        <%= f.email_field :email, class: "form-control" %>
        <span class="help-block">邮箱地址</span>
      </div>
      <div class="col-md-2">
        <%= f.text_field :tencent, class: "form-control" %>
        <span class="help-block">QQ</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :address, "地址", class: "control-label col-md-2" %>
      <div class="col-md-6">
        <%= f.text_field :address, class: "form-control" %>
        <span class="help-block">终端的详细地址("XX省XX市XX街道XX路XX号")</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :idcard, "身份信息", class: "control-label col-md-2" %>
      <div class="col-md-3">
        <%= f.text_field :idcard, class: "form-control" %>
        <span class="help-block">身份证号码</span>
      </div>
      <div class="col-md-2">
        <%= f.text_field :nation, class: "form-control" %>
        <span class="help-block">籍贯</span>
      </div>
      <div class="col-md-2">
        <%= f.select :marital, ["未婚","已婚","离异"], {include_blank: true}, {class: "form-control"} %>
        <span class="help-block">婚姻状况</span>
      </div>
      <div class="col-md-1">
        <%= f.select :zodiac, ["鼠","牛","虎","兔","龙","蛇","马","羊","猴","鸡","狗","猪"], {include_blank: true}, {class: "form-control"} %>
        <span class="help-block">生肖</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :hobby, "生活", class: "control-label col-md-2" %>
      <div class="col-md-3">
        <%= f.text_field :hobby, class: "form-control" %>
        <span class="help-block">兴趣爱好(","分割)</span>
      </div>
      <div class="col-md-2">
        <%= f.select :height, (140..200) , {include_blank: true}, {class: "form-control"} %>
        <span class="help-block">身高(cm)</span>
      </div>
      <div class="col-md-2">
        <%= f.select :weight, (40..100) , {include_blank: true}, {class: "form-control"} %>
        <span class="help-block">体重(kg)</span>
      </div>
      <div class="col-md-1">
        <%= f.select :blood, ["A","B","O","AB","其他"], {include_blank: true}, {class: "form-control"} %>
        <span class="help-block">血型</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :school, "学术", class: "control-label col-md-2" %>
      <div class="col-md-3">
        <%= f.text_field :school, class: "form-control" %>
        <span class="help-block">毕业学校</span>
      </div>
      <div class="col-md-3">
        <%= f.text_field :science, class: "form-control" %>
        <span class="help-block">学术头衔</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :note, "备注说明", class: "control-label col-md-2" %>
      <div class="col-md-6">
        <%= f.text_field :note, class: "form-control" %>
      </div>
    </div>
    <div class="form-group form-actions">
      <div class="col-md-10 col-md-offset-2">
        <button type="reset" class="btn btn-danger"><i class="icon-repeat"></i> 重置</button>
        <button type="submit" class="btn btn-success"><i class="icon-ok"></i> 提交</button>
      </div>
    </div>
    <% end %>
    <% if @contact.new_record?() %>
    <h4 class="sub-header">上传模板数据</h4>
    <%= form_tag import_contacts_path, multipart: true, class: "form-horizontal" do %>
    <div class="form-group">
      <label class="control-label col-md-2" for="file">目标数据模板</label>
      <div class="col-md-4">
        <%= file_field_tag :file, class: "form-control" %>
      </div>
      <div class="col-md-4">
        <%= link_to "模板下载", templete_contacts_url(format: :xls) %>
      </div>
    </div>  
    <div class="form-group form-actions">
      <div class="col-md-10 col-md-offset-2">
        <button type="submit" class="btn btn-success"><i class="icon-cloud-upload"></i> 上传</button>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/contacts/edit.html.erb
<% provide(:page_title, page_title("glyphicon-shopping_bag","修改联系人","这里修改联系人的详细信息")) %>
<%= render 'form' %>

app/views/contacts/index.html.erb
<% provide(:page_title, page_title("glyphicon-shopping_bag","联系人目录","这里可以查询所有联系人信息")) %>
<div class="block-section">
  <table class="ddatatabless table table-bordered table-hover" data-source="<%= contacts_url(format: "json") %>">
    <thead>
      <tr>
        <th><i class="icon-user"></i> 姓名</th>
        <th> 所属终端</th>
        <th> 部门</th>
        <th> 职务</th>
        <th> 联系方式</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<% provide(:page_title, page_title("glyphicon-shopping_bag","新增联系人","这里添加联系人的详细信息")) %>
<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @contact.department %>
</p>

<p>
  <strong>Duty:</strong>
  <%= @contact.duty %>
</p>

<p>
  <strong>Workspace:</strong>
  <%= @contact.client.name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @contact.sex %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @contact.birthdate %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @contact.mobile %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @contact.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Tencent:</strong>
  <%= @contact.tencent %>
</p>

<p>
  <strong>Idcard:</strong>
  <%= @contact.idcard %>
</p>

<p>
  <strong>Hobby:</strong>
  <%= @contact.hobby %>
</p>

<p>
  <strong>Nation:</strong>
  <%= @contact.nation %>
</p>

<p>
  <strong>Marital:</strong>
  <%= @contact.marital %>
</p>

<p>
  <strong>Blood:</strong>
  <%= @contact.blood %>
</p>

<p>
  <strong>Height:</strong>
  <%= @contact.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @contact.weight %>
</p>

<p>
  <strong>Zodiac:</strong>
  <%= @contact.zodiac %>
</p>

<p>
  <strong>School:</strong>
  <%= @contact.school %>
</p>

<p>
  <strong>Science:</strong>
  <%= @contact.science %>
</p>

<p>
  <strong>Note:</strong>
  <%= @contact.note %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/templete.xls.erb
<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="目标客户档案模板">
    <Table>
      <Row ss:Hidden="1">
        <Cell><Data ss:Type="String">name</Data></Cell>
        <Cell><Data ss:Type="String">client_id</Data></Cell>
        <Cell><Data ss:Type="String">department</Data></Cell>
        <Cell><Data ss:Type="String">duty</Data></Cell>
        <Cell><Data ss:Type="String">sex</Data></Cell>
        <Cell><Data ss:Type="String">birthdate</Data></Cell>
        <Cell><Data ss:Type="String">address</Data></Cell>
        <Cell><Data ss:Type="String">mobile</Data></Cell>
        <Cell><Data ss:Type="String">tel</Data></Cell>
        <Cell><Data ss:Type="String">email</Data></Cell>
        <Cell><Data ss:Type="String">tencent</Data></Cell>
        <Cell><Data ss:Type="String">idcard</Data></Cell>
        <Cell><Data ss:Type="String">hobby</Data></Cell>
        <Cell><Data ss:Type="String">matital</Data></Cell>
        <Cell><Data ss:Type="String">blood</Data></Cell>
        <Cell><Data ss:Type="String">height</Data></Cell>
        <Cell><Data ss:Type="String">nation</Data></Cell>
        <Cell><Data ss:Type="String">zodiac</Data></Cell>
        <Cell><Data ss:Type="String">weight</Data></Cell>
        <Cell><Data ss:Type="String">school</Data></Cell>
        <Cell><Data ss:Type="String">science</Data></Cell>
        <Cell><Data ss:Type="String">note</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">MDR姓名</Data></Cell>
        <Cell><Data ss:Type="String">所属终端</Data></Cell>
        <Cell><Data ss:Type="String">科室</Data></Cell>
        <Cell><Data ss:Type="String">职务</Data></Cell>
        <Cell><Data ss:Type="String">性别</Data></Cell>
        <Cell><Data ss:Type="String">出生日期</Data></Cell>
        <Cell><Data ss:Type="String">家庭住址</Data></Cell>
        <Cell><Data ss:Type="String">手机</Data></Cell>
        <Cell><Data ss:Type="String">座机</Data></Cell>
        <Cell><Data ss:Type="String">邮箱地址</Data></Cell>
        <Cell><Data ss:Type="String">QQ</Data></Cell>
        <Cell><Data ss:Type="String">身份证号码</Data></Cell>
        <Cell><Data ss:Type="String">兴趣爱好</Data></Cell>
        <Cell><Data ss:Type="String">婚姻状况</Data></Cell>
        <Cell><Data ss:Type="String">血型</Data></Cell>
        <Cell><Data ss:Type="String">身高</Data></Cell>
        <Cell><Data ss:Type="String">籍贯</Data></Cell>
        <Cell><Data ss:Type="String">生肖</Data></Cell>
        <Cell><Data ss:Type="String">体重</Data></Cell>
        <Cell><Data ss:Type="String">毕业院校</Data></Cell>
        <Cell><Data ss:Type="String">学术地位</Data></Cell>
        <Cell><Data ss:Type="String">备注说明</Data></Cell>
      </Row>
    </Table>
  </Worksheet>
</Workbook>