config/routes.rb
Neptune::Application.routes.draw do
  resources :contacts do
    collection do
      post :import
      get :templete
    end
  end

  resources :clients do
    collection { post :import }
  end

  resources :products do
    collection { post :import }
  end

  devise_for :users

  root 'home#index'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
	include OpenSpreadsheet

	def self.import(file)
		spreadsheet = open_spreadsheet(file)
		header = spreadsheet.row(1)
		(2..spreadsheet.last_row).each do |i|
			row = Hash[[header, spreadsheet.row(i)].transpose]
			product = find_by_id(row["id"]) || new
			product.attributes = row.to_hash.slice(*Product.attribute_names())
			product.save!
		end
	end

	def self.export
		CSV.generate do |csv|
      		csv << column_names
      		all.each do |product|
        		csv << product.attributes.values_at(*column_names)
      		end
    	end
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def import
    Product.import(params[:file])
    redirect_to products_url, notice: "Products imported."
  end

  def export
    respond_to do |format|
      format.xls { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  private
    
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :shortname, :shortcode, :bid_price, :final_price, :intro, :factory, :spec, :unit)
    end
end

app/views/products/_form.html.erb
<div class="block block-themed block-last">
  <div class="block-title">
    <h4>General Form Elements &amp; Components</h4>
  </div>
  <div class="block-content">
    <h4 class="sub-header">基本数据</h4>
    <%= form_for(@product, html: { class: "form-horizontal" }) do |f| %>
    <div class="form-group">
      <%= f.label :name, "药品名称", class: "control-label col-md-2" %>
      <div class="col-md-3">
        <%= f.text_field :name, class: "form-control" %>
        <span class="help-block">填写药品的完整名称</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :factory, "生产厂家", class: "control-label col-md-2" %>
      <div class="col-md-3">
       <%= f.text_field :factory, class: "form-control" %>
        <span class="help-block">生产厂家的全称</span>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :spec, "规格", class: "control-label col-md-2" %>
      <div class="col-md-3">
       <%= f.text_field :spec, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :shortname, "助记", class: "control-label col-md-2" %>
      <div class="col-md-3">
        <%= f.text_field :shortname, class: "form-control", placeholder: "助记名称..." %>
      </div>
      <div class="col-md-3">
        <%= f.text_field :shortcode, class: "form-control", placeholder: "助记代码..." %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :bid_price, "价格", class: "control-label col-md-2" %>
      <div class="col-md-3">
        <%= f.text_field :bid_price, class: "form-control", placeholder: "结算价..." %>
      </div>
      <div class="col-md-3">
        <%= f.text_field :final_price, class: "form-control", placeholder: "挂网价..." %>
      </div>
    </div>
    <div class="form-group">
     <%= f.label :intro, "药品简介", class: "control-label col-md-2" %>
      <div class="col-md-6">
        <%= f.text_area :intro, class: "form-control", size: "6x6", placeholder: "..." %>
      </div>
    </div>
    <div class="form-group form-actions">
      <div class="col-md-10 col-md-offset-2">
        <button type="reset" class="btn btn-danger"><i class="icon-repeat"></i> 重置</button>
        <button type="submit" class="btn btn-success"><i class="icon-ok"></i> 提交</button>
      </div>
    </div>
    <% end %>
    <h4 class="sub-header">上传模板数据</h4>
    <%= form_tag import_products_path, multipart: true, class: "form-horizontal" do %>
    <div class="form-group">
      <label class="control-label col-md-2" for="file">目标数据模板</label>
      <div class="col-md-4">
        <%= file_field_tag :file, class: "form-control" %>
      </div>
    </div>  
    <div class="form-group form-actions">
      <div class="col-md-10 col-md-offset-2">
        <button type="submit" class="btn btn-success"><i class="icon-cloud-upload"></i> 上传</button>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/products/ba.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :shortcode %><br>
    <%= f.text_field :shortcode %>
  </div>
  <div class="field">
    <%= f.label :bid_price %><br>
    <%= f.text_field :bid_price %>
  </div>
  <div class="field">
    <%= f.label :final_price %><br>
    <%= f.text_field :final_price %>
  </div>
  <div class="field">
    <%= f.label :intro %><br>
    <%= f.text_area :intro %>
  </div>
  <div class="field">
    <%= f.label :factory %><br>
    <%= f.text_field :factory %>
  </div>
  <div class="field">
    <%= f.label :spec %><br>
    <%= f.text_field :spec %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% provide(:page_title, page_title("glyphicon-shopping_bag","修改品种","这里修改品种的详细信息")) %>
<%= render 'form' %>

app/views/products/index.html.erb
<% provide(:page_title, page_title("glyphicon-shopping_bag","品种一览","这里列出了所有的品种")) %>

<div class="btn-group btn-group-sm pull-right">
  <button class="btn btn-default" data-toggle="tooltip" title="Table Settings"><i class="icon-cog"></i></button>
  <button class="btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="icon-angle-down"></i></button>
  <ul class="dropdown-menu">
    <li><a href="<%= new_product_url %>"><i class="icon-plus"></i> 新增品种</a></li>
    <li><a href="javascript:void(0)"><i class="icon-file-alt"></i> 导入模板数据</a></li>
    <li class="divider"></li>
    <li><a href="javascript:void(0)"><i class="icon-external-link"></i> 导出数据</a></li>
  </ul>
</div>
<div class="block block-themed block-last">
  <div class="block-title">
    <h4><i class="icon-asterisk"></i> Showing 10 out of 50 Products</h4>
  </div>
  <div class="block-content">
    <div class="row row-items">
      <div class="col-md-3">
        <div class="block">
          <div class="block-title">
            <h4>品种分类</h4>
          </div>
          <div class="block-content full">
            <ul class="nav nav-pills nav-stacked remove-margin">
              <li class="active"><a href="javascript:void(0)">Category #1</a></li>
              <li><a href="javascript:void(0)">Category #2</a></li>
              <li><a href="javascript:void(0)">Category #3</a></li>
              <li><a href="javascript:void(0)">Category #4</a></li>
              <li><a href="javascript:void(0)">Category #5</a></li>
              <li><a href="javascript:void(0)">Category #6</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9">
        <% @products.each do |product| %>
        <div class="row row-items">
          <div class="col-sm-2">
            <a href="javascript:void(0)">
              <img src="/assets/placeholders/image_160x120_dark.png" class="img-responsive" alt="Image">
            </a>
          </div>
          <div class="col-sm-6 content-text">
            <h4 class="media-heading"><%= link_to product.name, product %> <small><%= product[:spec] %></small></h4>
            <p><%= product[:factory] %><br><strong><%= product[:shortname] %>( <%= product[:shortcode] %> )</strong></p>
            <p>Available: <strong>50</strong></p>
          </div>
          <div class="col-sm-4 push text-right">
            <h4 class="sub-header text-black">$ 983,00</h4>
            <a href="page_ready_shopping_cart.php" class="btn btn-warning"><i class="icon-shopping-cart"></i> Add to cart</a>
            <a href="javascript:void(0)" class="btn btn-success">Buy now</a>
          </div>
        </div>
        <% end %>
        <div class="text-center">
          <ul class="pagination">
            <li class="disabled"><a href="javascript:void(0)">Prev</a></li>
            <li class="active"><a href="javascript:void(0)">1</a></li>
            <li><a href="javascript:void(0)">2</a></li>
            <li><a href="javascript:void(0)">3</a></li>
            <li><a href="javascript:void(0)">4</a></li>
            <li><a href="javascript:void(0)">5</a></li>
            <li><a href="javascript:void(0)">Next</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.xls.erb
<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/products/new.html.erb
<% provide(:page_title, page_title("glyphicon-shopping_bag","新增品种","这里添加品种的详细信息")) %>
<%= render 'form' %>

app/views/products/show.html.erb
<div class="heading-buttons">
  <h3><%= @product[:name] %><span>  <%= @product[:factory] %></span></h3>
  <div class="buttons pull-right">
    <a href="<%= products_url %>" class="btn glyphicons btn-icon btn-default btn-small left_arrow"><i></i> 回到列表</a>
  </div>
  <div class="clearfix"></div>
</div>
<div class="separator bottom"></div>
<div class="innerLR">
  <!-- Product details -->
  <div class="shop-client-products product-details">
    <!-- Row -->
    <div class="row-fluid">
    
      <!-- Product Gallery -->
      <div class="span7" data-toggle="modal-gallery" data-target="#modal-gallery" id="gallery-5" data-delegate="#gallery-5">
        <a class="thumb" href="/assets/gallery-2/1.jpg" data-gallery="gallery"><img src="/assets/gallery-2/1.jpg" alt="photo" /></a>
        <div class="separator bottom"></div>
      </div>
      <!-- // Product Gallery END -->
      
      <div class="span5">
        <form class="margin-bottom-none form-horizontal">
        
          <!-- Price -->
          <div class="box">
            <div class="control-group">
              <label class="control-label">中标价</label>
              <div class="controls"><span class="price">￥<%= @product[:bid_price] %></span></div>
              <label class="control-label">回款价</label>
              <div class="controls"><span class="price">￥<%= @product[:final_price] %></span></div>
              <div class="ribbon-wrapper"><div class="ribbon primary">价格</div></div>
            </div>
          </div>
          <!-- // Price END -->
          
          <!-- Purchase Options -->
          <div class="box">
            <div class="control-group">
              <label class="control-label">规格</label>
              <div class="controls"><%= @product[:spec] %></div>
            </div>
            <div class="control-group">
              <label class="control-label">单位</label>
              <div class="controls"><%= @product[:unit] %></div>
            </div>
          </div>
          <!-- // Purchase Options END -->

          <!-- Purchase Options -->
          <div class="box">
            <div class="control-group">
              <label class="control-label">缩写</label>
              <div class="controls"><%= @product[:shortname] %></div>
            </div>
            <div class="control-group">
              <label class="control-label">短位码</label>
              <div class="controls"><%= @product[:shortcode] %></div>
            </div>
          </div>
          <!-- // Purchase Options END -->
          
          <!-- Add to cart / Share -->
          <div class="row-fluid">
            <div class="span6"><a href="<%= edit_product_url(@product) %>" class="btn btn-icon glyphicons pencil btn-primary btn-block"><i></i>修改产品</a></div>
            <div class="span6"><a href="<%= product_url(@product) %>" data-confirm = "Are you sure?", data-method = "delete" class="btn btn-icon glyphicons remove btn-primary btn-block"><i></i>删除产品</a></div>
          </div>
          <!-- // Add to cart / Share END -->
          
        </form>
      </div>
    </div>
    <!-- // Row END -->
    
    <!-- Product description -->
    <div class="box">
      <h5>产品介绍</h5>
      <%= sanitize @product[:intro] %>
    </div>
    <!-- // Product description END -->
    
  </div>
  <div class="separator bottom"></div>
  <!-- // Product details END -->
  
  <!-- Product reviews & delivery -->
  <div class="widget widget-tabs widget-quick">
  
    <!-- Widget heading -->
    <div class="widget-head">
      <ul>
        <li class="active"><a href="#reviewsTab" data-toggle="tab" class="glyphicons star"><i></i>Reviews</a></li>
        <li><a href="#deliveryTab" data-toggle="tab" class="glyphicons car"><i></i>Delivery</a></li>
      </ul>
    </div>
    <!-- // Widget heading END -->
    
    <div class="widget-body">
      <div class="tab-content">
      
        <!-- Delivery Tab -->
        <div class="tab-pane" id="deliveryTab">
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas convallis porta purus, pulvinar mattis nulla tempus ut. Curabitur quis dui orci. Ut nisi dolor, dignissim a aliquet quis, vulputate id dui. Proin ultrices ultrices ligula, dictum varius turpis faucibus non. Curabitur faucibus ultrices nunc, nec aliquet leo tempor cursus. Pellentesque sed felis ipsum. Quisque in lacus sed ante malesuada condimentum et a risus. Morbi accumsan euismod rutrum. Etiam vitae turpis eu est lacinia condimentum a sit amet erat. Sed augue turpis, lobortis ac feugiat eget, cursus ac justo.</p>
        </div>
        <!-- // Delivery Tab END -->
        
        <!-- Reviews Tab -->
        <div class="tab-pane active" id="reviewsTab">
        
          <!-- Media item -->
          <div class="media">
            <img class="media-object pull-left thumb" src="theme/images/mrawesome.jpg" alt="">
            <div class="media-body">
              <blockquote>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vitae accumsan mauris. Donec vitae nibh felis, facilisis bibendum sapien. Duis a odio id erat scelerisque fermentum in ut leo. Suspendisse potenti. Nunc semper cursus dui luctus porttitor. Donec facilisis semper magna sit amet ullamcorper. Cras rutrum magna eget risus vulputate congue. Sed sem libero, dignissim sit amet viverra vitae, suscipit sit amet elit. Integer tincidunt risus in metus rhoncus molestie.</p>
                  <small><a href="#" title="">John Doe</a><cite> | client @ Famous Company</cite></small>
              </blockquote>
            </div>
          </div>
          <!-- // Media item END -->
          
        </div>
        <!-- // Reviews Tab END -->
      
      </div>
    </div>
  </div>
  <!-- // Product reviews & delivery END -->
  
</div>